=== dkujnisc/Seminararbeit_Kujnisch/consoles.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT collection (console+) >
    <!ELEMENT console (console_name, console_publisher, console_year, console_type)>
        <!ATTLIST console
          id ID #REQUIRED>
        <!ELEMENT console_name (#PCDATA)>
            <!ATTLIST console_name
                attribut1 CDATA #REQUIRED
                attribut2 CDATA #REQUIRED>
        <!ELEMENT console_publisher (#PCDATA)>
        <!ELEMENT console_year (#PCDATA)>
        <!ELEMENT console_type (#PCDATA)>

=== dkujnisc/Seminararbeit_Kujnisch/consoles.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE collection SYSTEM "consoles.dtd">

<collection>
<console id='gameboy'>
    <console_name attribut1='attribut1' attribut2='attribut2'>Gameboy</console_name>
    <console_publisher>Nintendo</console_publisher>
    <console_year>1989</console_year>
    <console_type>Handheld-Konsole</console_type>
</console>

<console id='sms'>
    <console_name attribut1='attribut1' attribut2='attribut2'>Sega Master System</console_name>
    <console_publisher>Sega</console_publisher>
    <console_year>1985</console_year>
    <console_type>Station채re Spielkonsole</console_type>
</console>

<console id='smd'>
    <console_name attribut1='attribut1' attribut2='attribut2'>Sega Mega Drive</console_name>
    <console_publisher>Sega</console_publisher>
    <console_year>1988</console_year>
    <console_type>Station채re Spielkonsole</console_type>
</console>

<console id='ps2'>
    <console_name attribut1='attribut1' attribut2='attribut2'>Sony PlayStation 2</console_name>
    <console_publisher>Sony</console_publisher>
    <console_year>2000</console_year>
    <console_type>Station채re Spielkonsole</console_type>
</console>

<console id='ps4'>
    <console_name attribut1='attribut1' attribut2='attribut2'>Sony PlayStation 4</console_name>
    <console_publisher>Sony</console_publisher>
    <console_year>2013</console_year>
    <console_type>Station채re Spielkonsole</console_type>
</console>    
</collection>
